---
abstract: 'CPAN Authors with GitHub repositories'
author:
  - 'gray <gray@cpan.org>'
build_requires:
  Test::More: 0.82
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-GitHub
no_index:
  directory:
    - t
    - inc
    - scripts
requires:
  Acme::CPANAuthors: 0.14
resources:
  repository: http://github.com/gray/acme-cpanauthors-github
version: 0.05
